Repository kubernetes/utils, pull requests merged in 2018-10, with the labels that each got.

#49 Support os/exec.Cmd.Env
  exec/exec.go
  exec/exec_test.go
  exec/testing/fake_exec.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#50 copy k8s.io/kubernetes/pkg/util/io to k8s.io/utils/io
  io/consistentread.go
Labels: approved, cncf-cla: no, kind/feature, lgtm, size/M

#52 copy k8s.io/kubernetes/pkg/util/nsenter to k8s.io/utils/nsenter
  .travis.yml
  nsenter/OWNERS
  nsenter/exec.go
  nsenter/exec_unsupported.go
  nsenter/nsenter.go
  nsenter/nsenter_test.go
  nsenter/nsenter_unsupported.go
Labels: cncf-cla: no, kind/feature, lgtm, size/XL

#53 Install realpath during testing in travis
  .travis.yml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#54 add tests for io and update README
  README.md
  io/consistentread.go
  io/consistentread_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L
