Repository kubernetes/utils, pull requests merged in 2018-11, with the labels that each got.

#58 add @andrewsykim @cheftako and @mcrute as reviewers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#60 [exec] Implement Start, Wait & StdIOPipe methods
  exec/exec.go
  exec/exec_test.go
  exec/stdiopipe_test.go
  exec/testing/fake_exec.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#59 Add Makefile and build scripts
  .travis.yml
  Makefile
  hack/verify-gofmt.sh
  hack/verify-golint.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#61 [exec] Fix godoc Example
  exec/stdiopipe_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
