Repository kubernetes/utils, pull requests merged in 2019-12, with the labels that each got.

#123 feature: implement Output method for FakeCmd
  exec/testing/fake_exec.go
  mount/safe_format_and_mount_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#127 Validate the existence of filesystem before attempting to mount it (linux)
  mount/mount_linux.go
  mount/safe_format_and_mount_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/L

#128 Add myself as reviewer for mount directory
  mount/OWNERS
Labels: approved, cncf-cla: yes, lgtm, sig/storage, size/XS
