Repository kubernetes/utils, pull requests merged in 2019-05, with the labels that each got.

#89 Add go module support
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#88 Add a new func `ReadAtMost` and rename the file
  io/read.go
  io/read_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#93 Add Trace example and update documentation
  trace/trace.go
  trace/trace_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, size/S

#92 Fix typos in documentation
  README.md
  pointer/pointer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
