Repository kubernetes/utils, pull requests merged in 2019-02, with the labels that each got.

#79 Updated OWNERS to be consistent across k8s repos
  OWNERS
  nsenter/OWNERS
  pointer/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#80 semantic: add forked reflect based DeepEqual
  semantic/deep_equal.go
  semantic/deep_equal_test.go
  third_party/forked/golang/LICENSE
  third_party/forked/golang/PATENTS
  third_party/forked/golang/reflect/README.md
  third_party/forked/golang/reflect/deep_equal.go
  third_party/forked/golang/reflect/deep_equal_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#77 remove BAZEL build files
  keymutex/BUILD
  net/BUILD
  strings/BUILD
Labels: approved, cncf-cla: yes, lgtm, size/L

#82 Move object diff and field path from apimachinery
  diff/diff.go
  diff/diff_test.go
  field/path.go
  field/path_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#84 fix negative slice index error in keymutex
  keymutex/hashed.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
