Repository kubernetes/utils, pull requests merged in 2019-08, with the labels that each got.

#105 Add fields to trace to allow for consistent paramaterization and to avoid needless string concatenation
  trace/trace.go
  trace/trace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#107 add ParsePort from kubeadm code
  net/net.go
  net/net_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#111 Trim down travis to latest Go versions
  .travis.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S
