Repository kubernetes/utils, pull requests merged in 2019-09, with the labels that each got.

#108 Changing AtoI to uParseInt to handle overflow problems.
  net/net.go
  net/net_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#112 adding functions for ipallocator
  net/net.go
  net/net_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#115 fix: ineffect assign and misspell
  exec/exec_test.go
  net/net_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
