Repository kubernetes/utils, pull requests merged in 2019-01, with the labels that each got.

#64 Volunteer to help with k8s.io/utils
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#68 k8s.io/utils should use klog
  nsenter/exec.go
  nsenter/nsenter.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#67 Add integer from k/k repo
  integer/integer.go
  integer/integer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#65 Add trace from k/k repo
  trace/trace.go
Labels: approved, cncf-cla: no, lgtm, size/M

#73 Consolidate the Nsenter implementations (new name NSEnter)
  nsenter/exec.go
  nsenter/exec_unsupported.go
  nsenter/nsenter.go
  nsenter/nsenter_test.go
  nsenter/nsenter_unsupported.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#57 copy k8s.io/kubernetes/pkg/util/net to k8s.io/util/net
  net/BUILD
  net/OWNERS
  net/ipnet.go
  net/ipnet_test.go
  net/net.go
  net/net_test.go
Labels: approved, cncf-cla: no, kind/feature, lgtm, size/XL

#55 Move pkg util strings/keymutex from kubernetes kubernetes
  keymutex/BUILD
  keymutex/hashed.go
  keymutex/keymutex.go
  keymutex/keymutex_test.go
  strings/BUILD
  strings/escape.go
  strings/escape_test.go
  strings/line_delimiter.go
  strings/line_delimiter_test.go
  strings/strings.go
  strings/strings_test.go
Labels: approved, cncf-cla: no, lgtm, size/XL

#51 copy k8s.io/kubernetes/pkg/util/file to k8s.io/utils/file
  path/file.go
  path/file_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#74 keymutex: remove glog usage
  keymutex/hashed.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#72 Adds UT for trace package in utils
  trace/trace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
