Repository kubernetes/utils, pull requests merged in 2020-10, with the labels that each got.

#190 Factor PassiveClock out of Clock
  clock/clock.go
  clock/testing/fake_clock.go
  clock/testing/fake_clock_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#188 fix: smb valid path error
  mount/mount_windows.go
  mount/mount_windows_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#193 test: add windows unit test action
  .github/workflows/test.yml
  mount/mount_windows_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S
