Repository kubernetes/utils, pull requests merged in 2020-04, with the labels that each got.

#154 Switch to GitHub actions for better cross platform testing
  .github/workflows/test.yml
  Makefile
  mount/mount.go
  mount/mount_helper_unix.go
  mount/mount_linux.go
  temp/temptest/dir_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#156 Ensure we can build fine under windows
  .github/workflows/test.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#152 Switch to klog v2
  go.mod
  go.sum
  mount/fake_mounter.go
  mount/mount_helper_common.go
  mount/mount_helper_windows.go
  mount/mount_linux.go
  mount/mount_windows.go
  nsenter/nsenter.go
  trace/trace.go
  trace/trace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#157 Remove .travis.yml
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#158 Add apidiff script to check go signature changes
  .github/workflows/test.yml
  Makefile
  hack/verify-apidiff.sh
Labels: approved, cncf-cla: yes, lgtm, size/L
