Repository kubernetes/utils, pull requests merged in 2020-07, with the labels that each got.

#175 Add ebtables from kubernetes.
  .gitignore
  net/ebtables/ebtables.go
  net/ebtables/ebtables_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#177 trace: on klog.V(4) only log all nested traces inside trace above threshold
  trace/trace.go
  trace/trace_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#179 Remove driver letter assignment during volume format
  mount/mount_windows.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#182 Fix tracing reporting
  trace/trace.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#183 Add PtrDerefOr for more types
  pointer/pointer.go
  pointer/pointer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
