Repository kubernetes/utils, pull requests merged in 2021-07, with the labels that each got.

#209 LRU - seeded from github.com/golang/groupcache
  internal/third_party/forked/golang/golang-lru/lru.go
  lru/lru.go
  lru/lru_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#208 Add string slice functions
  strings/slices/slices.go
  strings/slices/slices_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#212 Introduce WithTicker clock
  clock/clock.go
  clock/testing/fake_clock.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#213 Introduced SimpleIntervalClock
  clock/testing/fake_clock.go
  clock/testing/simple_interval_clock.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M
