Repository kubernetes/utils, pull requests merged in 2021-05, with the labels that each got.

#191 Provide a message on the mount directory to warn the users
  mount/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#205 Add explicit error to ConsistentRead
  io/read.go
  io/read_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#206 Fix tracing time format, to report second
  trace/trace.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS
