Repository kubernetes/utils, pull requests merged in 2021-08, with the labels that each got.

#215 Add int pointer function
  pointer/pointer.go
  pointer/pointer_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#216 lru: use read/write lock for lru get
  lru/lru.go
  lru/lru_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, kind/bug

#217 Fix lint
  lru/lru_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved
