Repository kubernetes/utils, pull requests merged in 2022-11, with the labels that each got.

#268 pointer: make deprecation comments follow convention
  pointer/pointer.go
Labels: cncf-cla: yes, lgtm, size/S, approved, kind/cleanup

#270 Fix trace panic when concurrently adding children
  trace/trace.go
  trace/trace_test.go
Labels: cncf-cla: yes, lgtm, size/M, kind/failing-test, approved

#265 Fix an API accident with net.IPFamily
  net/port.go
Labels: cncf-cla: yes, lgtm, size/XS, sig/network, approved, kind/cleanup, kind/api-change

#271 Add IPFamilyOf() / IPFamilyOfString() / IPFamilyOfCIDR() / IPFamilyOfCIDRString()
  net/ipfamily.go
  net/ipfamily_test.go
  net/net.go
  net/net_test.go
  net/port.go
Labels: cncf-cla: yes, lgtm, size/XXL, kind/feature, sig/network, approved
