Repository kubernetes/utils, pull requests merged in 2022-08, with the labels that each got.

#254 Bump version of golang to 1.19
  .github/workflows/test.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#253 add uint64 and uint to pointer pkg
  pointer/pointer.go
  pointer/pointer_test.go
Labels: cncf-cla: yes, lgtm, size/L, kind/feature, approved

#242 Ineffective break statements triggering SA4011
  mount/mount.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, kind/cleanup
