Repository kubernetes/utils, pull requests merged in 2023-02, with the labels that each got.

#274 Make FakeExec safe for concurrency
  exec/testing/fake_exec.go
Labels: cncf-cla: yes, lgtm, size/M, kind/feature, approved

#275 lru: add support for setting eviction func
  lru/lru.go
  lru/lru_test.go
Labels: cncf-cla: yes, lgtm, size/S, kind/feature, approved

#276 Fix fsnotify util upstream link and suggest newer version.
  inotify/README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, kind/cleanup
